const mongoose=require('mongoose');
const schema=mongoose.Schema;

let userSchema=new schema(
    {
        userId:
        {
            type:String,
            default:'',
            index:true,
            unique:true,
        },
        firstName:
        {
            type:String,
            default:''
        },
        lastName:
        {
            type:String,
            default:''
        },
        userName:
        {
            type:String,
            default:''
        },
        countryName:
        {
            type:String,
            default:''
        },
        mobileNumber:
        {
            type:String,
            default:''
        },
        email:
        {
            type:String,
            default:''
        },
        password:
        {
            type:String,
            default:'DefaultP@ssw0rd'
        },
        isAdmin:
        {
            type:String,
            default:'false'
        },
        status:
        {
            type:String,
            default:'Offline'
        },
        validationToken:
        {
            type:String,
            default:''
        },
        emailVerified:
        {   
            type:String,
            default:'no'
        },
        createdOn:
        {
            type:Date,
            default:Date.now()
        },
        modifiedOn:
        {
            type:Date,
            default:Date.now()
        }

    }
);

mongoose.model('userModel',userSchema);
